user_revision.settings:
  type: config_object
  mapping:
    revision_mode:
      type: string
      label: 'Revision mode: disabled, required, optional'
    revision_default_enabled:
      type: boolean
      label: 'Create new revision by default if mode is optional'
    revision_user_log_enabled:
      type: boolean
      label: 'Allow users to leave revision log messages when editing their account'
    revision_keep_passwords:
      type: boolean
      label: 'Preserve the password revisions'
    revision_information_open:
      type: boolean
      label: 'Show the revision information on the form open by default'
